[package]
name = "algorithms"
version = "0.1.0"
authors = ["joakim_nilfjord <joakim.nilfjord@evry.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
